import fs from "node:fs";
import path from "node:path";
import type { RobotConfig } from "../config.js";
import { outPath } from "../config.js";
import { buildSurfaceMap } from "../surface/merge.js";
import { screenBrief, systemPrompt } from "./prompt.js";
import { testSuiteSchema, validateCase } from "./testcase.js";
import type { TestCase } from "./testcase.js";
import type { SurfaceMap } from "../types.js";
import type { Usage } from "../llm.js";
import { NO_USAGE, addUsage, askJson, describeModel, estimateCost } from "../llm.js";

export interface SynthOptions {
  screen?: string;
}

export async function synthesize(
  config: RobotConfig,
  options: SynthOptions = {},
): Promise<TestCase[]> {
  const map = await loadOrBuildSurface(config);
  const spec = fs.readFileSync(path.join(config.root, config.spec), "utf8");
  const roles = Object.keys(config.auth.users);

  const screens = options.screen
    ? map.screens.filter((screen) => screen.route.includes(options.screen!))
    : map.screens.filter((screen) => screen.reachable);

  if (screens.length === 0) {
    throw new Error(
      options.screen
        ? `No probed screen matches "${options.screen}"`
        : "No reachable screens in the surface map. Run `robot surface` first.",
    );
  }

  const system = systemPrompt(spec);
  const generated: TestCase[] = [];
  let usageTotal = NO_USAGE;

  console.log(`\n  using ${describeModel()}`);

  for (const screen of screens) {
    process.stdout.write(`  synthesising ${screen.route} … `);

    // The spec and the vocabulary are identical across screens, so the system prompt
    // is a stable cacheable prefix across the whole run.
    const { value: suite, usage } = await askJson({
      system,
      user: screenBrief(map, screen, map.schemas, roles),
      schema: testSuiteSchema,
      maxTokens: 16000,
    });
    usageTotal = addUsage(usageTotal, usage);
    if (!suite) {
      console.log("failed to parse a corpus");
      continue;
    }

    const kept: TestCase[] = [];
    const rejected: string[] = [];
    for (const testCase of suite.cases) {
      const problems = validateCase(testCase);
      if (problems.length > 0) {
        rejected.push(problems[0]);
        continue;
      }
      kept.push(testCase);
    }

    generated.push(...kept);
    console.log(
      `${kept.length} cases` + (rejected.length ? `, ${rejected.length} rejected` : ""),
    );
    for (const problem of rejected) console.log(`      dropped: ${problem}`);
  }

  writeCorpus(config, generated);
  report(config, generated, usageTotal);
  return generated;
}

async function loadOrBuildSurface(config: RobotConfig): Promise<SurfaceMap> {
  const cached = path.join(config.root, config.outDir, "surface.json");
  if (fs.existsSync(cached)) {
    return JSON.parse(fs.readFileSync(cached, "utf8")) as SurfaceMap;
  }
  return buildSurfaceMap(config);
}

/**
 * The corpus is an artifact, not an action: written to disk, reviewable, diffable,
 * committed. Stage 3 replays it with zero inference. Hand-written cases live in their
 * own files and are never overwritten.
 */
function writeCorpus(config: RobotConfig, cases: TestCase[]): void {
  const target = path.join(config.root, config.testcaseDir, "generated.json");
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(
    target,
    JSON.stringify(
      { _comment: "Generated by `robot synth`. Review before trusting.", cases },
      null,
      2,
    ),
  );
}

function report(config: RobotConfig, cases: TestCase[], usage: Usage): void {
  const bySource = cases.reduce<Record<string, number>>((acc, testCase) => {
    acc[testCase.assertionSource] = (acc[testCase.assertionSource] ?? 0) + 1;
    return acc;
  }, {});
  const byKind = cases.reduce<Record<string, number>>((acc, testCase) => {
    acc[testCase.kind] = (acc[testCase.kind] ?? 0) + 1;
    return acc;
  }, {});

  const cost = estimateCost(usage);

  console.log(`\n  ${cases.length} cases written to ${config.testcaseDir}/generated.json`);
  console.log(
    `  by source: ${Object.entries(bySource)
      .map(([k, v]) => `${k} ${v}`)
      .join("  ")}`,
  );
  console.log(
    `  by kind:   ${Object.entries(byKind)
      .map(([k, v]) => `${k} ${v}`)
      .join("  ")}`,
  );
  console.log(
    `  tokens:    ${usage.inputTokens} in, ${usage.outputTokens} out, ` +
      `${usage.cachedInputTokens} cached  (~$${cost.toFixed(3)})\n`,
  );

  fs.writeFileSync(
    outPath(config, "synth-usage.json"),
    JSON.stringify(
      { ...usage, model: describeModel(), cases: cases.length, estimatedCostUsd: cost },
      null,
      2,
    ),
  );
}
