import fs from "node:fs";
import path from "node:path";
import { zodOutputFormat } from "@anthropic-ai/sdk/helpers/zod";
import type { RobotConfig } from "../config.js";
import { outPath } from "../config.js";
import { buildSurfaceMap } from "../surface/merge.js";
import { screenBrief, systemPrompt } from "./prompt.js";
import { testSuiteSchema, validateCase } from "./testcase.js";
import type { TestCase } from "./testcase.js";
import type { SurfaceMap } from "../types.js";
import { MODEL, client, estimateCost, withApiErrors } from "../llm.js";

export interface SynthOptions {
  screen?: string;
}

export async function synthesize(
  config: RobotConfig,
  options: SynthOptions = {},
): Promise<TestCase[]> {
  const map = await loadOrBuildSurface(config);
  const spec = fs.readFileSync(path.join(config.root, config.spec), "utf8");
  const roles = Object.keys(config.auth.users);

  const screens = options.screen
    ? map.screens.filter((screen) => screen.route.includes(options.screen!))
    : map.screens.filter((screen) => screen.reachable);

  if (screens.length === 0) {
    throw new Error(
      options.screen
        ? `No probed screen matches "${options.screen}"`
        : "No reachable screens in the surface map. Run `robot surface` first.",
    );
  }

  const anthropic = client();
  const system = systemPrompt(spec);
  const generated: TestCase[] = [];
  let inputTokens = 0;
  let outputTokens = 0;
  let cacheReads = 0;

  for (const screen of screens) {
    process.stdout.write(`  synthesising ${screen.route} … `);

    const response = await withApiErrors(() =>
      anthropic.messages.parse({
        model: MODEL,
        max_tokens: 16000,
        thinking: { type: "adaptive" },
        // The spec and the vocabulary are identical across screens — cache them.
        system: [
          { type: "text", text: system, cache_control: { type: "ephemeral" } },
        ],
        messages: [
          { role: "user", content: screenBrief(map, screen, map.schemas, roles) },
        ],
        output_config: { format: zodOutputFormat(testSuiteSchema) },
      }),
    );

    inputTokens += response.usage.input_tokens;
    outputTokens += response.usage.output_tokens;
    cacheReads += response.usage.cache_read_input_tokens ?? 0;

    const suite = response.parsed_output;
    if (!suite) {
      console.log("failed to parse a corpus");
      continue;
    }

    const kept: TestCase[] = [];
    const rejected: string[] = [];
    for (const testCase of suite.cases) {
      const problems = validateCase(testCase);
      if (problems.length > 0) {
        rejected.push(problems[0]);
        continue;
      }
      kept.push(testCase);
    }

    generated.push(...kept);
    console.log(
      `${kept.length} cases` + (rejected.length ? `, ${rejected.length} rejected` : ""),
    );
    for (const problem of rejected) console.log(`      dropped: ${problem}`);
  }

  writeCorpus(config, generated);
  report(config, generated, { inputTokens, outputTokens, cacheReads });
  return generated;
}

async function loadOrBuildSurface(config: RobotConfig): Promise<SurfaceMap> {
  const cached = path.join(config.root, config.outDir, "surface.json");
  if (fs.existsSync(cached)) {
    return JSON.parse(fs.readFileSync(cached, "utf8")) as SurfaceMap;
  }
  return buildSurfaceMap(config);
}

/**
 * The corpus is an artifact, not an action: written to disk, reviewable, diffable,
 * committed. Stage 3 replays it with zero inference. Hand-written cases live in their
 * own files and are never overwritten.
 */
function writeCorpus(config: RobotConfig, cases: TestCase[]): void {
  const target = path.join(config.root, config.testcaseDir, "generated.json");
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(
    target,
    JSON.stringify(
      { _comment: "Generated by `robot synth`. Review before trusting.", cases },
      null,
      2,
    ),
  );
}

function report(
  config: RobotConfig,
  cases: TestCase[],
  usage: { inputTokens: number; outputTokens: number; cacheReads: number },
): void {
  const bySource = cases.reduce<Record<string, number>>((acc, testCase) => {
    acc[testCase.assertionSource] = (acc[testCase.assertionSource] ?? 0) + 1;
    return acc;
  }, {});
  const byKind = cases.reduce<Record<string, number>>((acc, testCase) => {
    acc[testCase.kind] = (acc[testCase.kind] ?? 0) + 1;
    return acc;
  }, {});

  const cost = estimateCost({
    input_tokens: usage.inputTokens,
    output_tokens: usage.outputTokens,
    cache_read_input_tokens: usage.cacheReads,
  });

  console.log(`\n  ${cases.length} cases written to ${config.testcaseDir}/generated.json`);
  console.log(
    `  by source: ${Object.entries(bySource)
      .map(([k, v]) => `${k} ${v}`)
      .join("  ")}`,
  );
  console.log(
    `  by kind:   ${Object.entries(byKind)
      .map(([k, v]) => `${k} ${v}`)
      .join("  ")}`,
  );
  console.log(
    `  tokens:    ${usage.inputTokens} in, ${usage.outputTokens} out, ` +
      `${usage.cacheReads} cached  (~$${cost.toFixed(3)})\n`,
  );

  fs.writeFileSync(
    outPath(config, "synth-usage.json"),
    JSON.stringify({ ...usage, cases: cases.length, estimatedCostUsd: cost }, null, 2),
  );
}
